### ISSUE TITLE
aggregating clob > 4000

### ISSUE THREAD

**Issue by tepal** [connormcd/listagg_clob#1]
the function fails, when aggregating clob objects larger then 4k

ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 7801, maximum: 4000)

select name, listagg_clob(clob_string) string
from X
group by name

**Comment by SteffanCline** [comment]
I get the same thing. I thought that's what the purpose of this was - to avoid the overflow errors then trunc the output to 4K as varchar2

**Comment by connormcd** [comment]
That's is not the aim of this tool.  "Standard" LISTAGG takes varchar2 and returns a concatenation that may be longer than the limit of varchar2.  LISTAGG_CLOB takes *varchar2* inputs and returns a clob to workaround the limitation of the *output* length.

(I'll update the readme to reflect this to avoid confusion)

**Comment by SteffanCline** [comment]
I am giving it varchar2 <= 4000 and still get an error that I'm over 4000 chars.
<pre>
ORA-12801: error signaled in parallel query server P026, instance pddcdbadm02.corp.intranet:dwops01p2 (2)
ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 4189, maximum: 4000)
12801. 00000 -  "error signaled in parallel query server %s"
*Cause:    A parallel query server reached an exception condition.
*Action:   Check the following error message for the cause, and consult
           your error manual for the appropriate action.
*Comment:  This error can be turned off with event 10397, in which
           case the server's actual error is signaled instead.</pre>
